### ISSUE TITLE
Update from 8.0.2 to 8.0.3 failed (missing function "first")

### ISSUE THREAD

**Issue by grafgraffy** [owncloud/updater#113]
When trying to update via the "online" app directly from owncloud I ran into following error Message:
'Serverfehler. Bitte überprüfe die Protokolldatei des Webservers, um weitere Details zu erhalten'
Which translates "server error, check the log of the webserver for details."
Did that and got:
PHP Fatal error:  Call to undefined function OCA\\Updater\\Location\\first() in /var/www/.../apps/updater/lib/location/apps.php on line 44, referer: ...index.php/apps/updater/update.php
I checked /apps/updater/lib/location.php for the missing function and indeed is not defined. 

Do I need to copy source in to get over it or do I need to manually update?

**Comment by karlitschek** [comment]
@VicDeo any idea what the problem might be?

**Comment by grafgraffy** [comment]
According to this:
https://github.com/owncloud/updater/commit/c9c8afb470ab7811b9249da0887f9380b8a86732#diff-a2507fbfbc040c95cabd0f0208804e1e
it was changed recently but the updater doesn't seem to respect/know it. I wonder if I can manually change it.

**Comment by VicDeo** [comment]
@grafgraffy surely, 8.0.3 contains has this fix https://github.com/owncloud/updater/pull/108/files but  8.0.0 and 8.0.2 don't

**Comment by grafgraffy** [comment]
I retried the update today and it worked, thanks for fixing.

**Comment by davidak** [comment]
i have an ownCloud 8.0.2 here and tried to update with the web updater (to 8.2.1) and got this error.

with the next http request i got the update page again, i must update to 8.2.2... get the error "Exception: Updates between multiple major versions and downgrades are unsupported." tried a few times... everything broken :/

```
{"reqId":"J6oi13OfZP8fG1V\/LvP5","remoteAddr":"","app":"core","message":"starting upgrade from 8.0.2.0 to 8.2.2.2","level":0,"time":"2016-04-05 14:25:32","method":"--","url":"--"}
{"reqId":"J6oi13OfZP8fG1V\/LvP5","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Updates between multiple major versions and downgrades are unsupported.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.2.2', '8.0.2.0')\\n#1 \\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/core\\\/command\\\/upgrade.php(213): OC\\\\Updater->upgrade()\\n#2 \\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Command\\\/Command.php(253): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#3 \\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(874): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#4 \\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(195): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#5 \\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(126): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(100): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#7 \\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/console.php(69): OC\\\\Console\\\\Application->run()\\n#8 \\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/client...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/lib\\\/private\\\/updater.php\",\"Line\":285}","level":3,"time":"2016-04-05 14:25:32","method":"--","url":"--"}
{"reqId":"9n61jQTC05ZiUJyDd0RF","remoteAddr":"195.50.152.102","app":"core","message":"starting upgrade from 8.0.2.0 to 8.2.2.2","level":0,"time":"2016-04-05 14:27:26","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=XTQdVD9EEFs5QgEnBlwUISkMJQxlPiIgeCsBISoh%3A3Ln2s7xirtYlp4PHxft93UvESDmLhF"}
{"reqId":"9n61jQTC05ZiUJyDd0RF","remoteAddr":"195.50.152.102","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Updates between multiple major versions and downgrades are unsupported.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.2.2', '8.0.2.0')\\n#1 \\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/clients\\\/client1\\\/web4\\\/web\\\/owncloud\\\/lib\\\/private\\\/updater.php\",\"Line\":285}","level":3,"time":"2016-04-05 14:27:26","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=XTQdVD9EEFs5QgEnBlwUISkMJQxlPiIgeCsBISoh%3A3Ln2s7xirtYlp4PHxft93UvESDmLhF"}
```

i don't want to update it manually, it is only a test instance.
