### ISSUE TITLE
BrokenUpdaterRepair SQL issue

### ISSUE THREAD

**Issue by PVince81** [owncloud/updater#331]
### Steps

1. Setup owncloud-9.0.0.tar.bz2
1. Go to admin page
1. Set channel to "daily"
1. Open updater
1. Start update

### Expected result
Updater runs fine

### Actual result
Hangs on "Updating core", CPU is at 100%, log contains these:
```
SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/db\\\/connection.php(205): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/db\\\/adapter.php(93): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/db\\\/connection.php(243): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*appconf...', Array, Array)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/appconfig.php(158): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*appconf...', Array, Array)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/allconfig.php(160): OC\\\\AppConfig->setValue('core', 'oc.integrityche...', '{\\\"core\\\":{\\\"EXTRA...')\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/integritycheck\\\/checker.php(431): OC\\\\AllConfig->setAppValue('core', 'oc.integrityche...', '{\\\"core\\\":{\\\"EXTRA...')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/integritycheck\\\/checker.php(544): OC\\\\IntegrityCheck\\\\Checker->storeResults('core', Array)\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/integritycheck\\\/checker.php(555): OC\\\\IntegrityCheck\\\\Checker->verifyCoreSignature()\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/repair\\\/brokenupdaterrepair.php(96): OC\\\\IntegrityCheck\\\\Checker->runInstanceVerification()\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/repair\\\/brokenupdaterrepair.php(102): OC\\\\Repair\\\\BrokenUpdaterRepair->recheckIntegrity()\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/repair.php(87): OC\\\\Repair\\\\BrokenUpdaterRepair->run()\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/updater.php(346): OC\\\\Repair->run()\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/updater.php(215): OC\\\\Updater->doUpgrade('9.0.1.3', '9.0.0.19')\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/core\\\/command\\\/upgrade.php(246): OC\\\\Updater->upgrade()\\n#16 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#17 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/core\\\/command\\\/base.php(158): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#18 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): OC\\\\Core\\\\Command\\\\Base->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#19 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#20 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#21 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#22 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/console.php(88): OC\\\\Console\\\\Application->run()\\n#23 \\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/occ(11): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#24 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloudtest\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":3,"time":"2016-04-26T09:36:13+00:00","method":"--","url":"--","user":"--"}
```

apparently related to BrokenUpdaterRepair.

Will attach the full log soon.

**Comment by PVince81** [comment]
```
% ls -l

-rw-r--r-- 1 wwwrun www  3737 Apr 26 11:36 .htaccess
-rw-r--r-- 1 wwwrun www   163 Apr 26 05:00 .user.ini
drwxr-xr-x 1 wwwrun www   592 Apr 26 11:33 3rdparty
-rw-r--r-- 1 wwwrun www  8065 Apr 26 05:00 AUTHORS
-rw-r--r-- 1 wwwrun www 34520 Apr 26 05:00 COPYING-AGPL
drwxrwxr-x 1 wwwrun www   578 Apr 26 11:33 __apps
drwxr-xr-x 1 wwwrun www    34 Apr 26 11:36 _oc_upgrade
drwxr-xr-x 1 wwwrun www     0 Apr 26 11:36 apps
drwxrwxr-x 1 wwwrun www    72 Apr 26 11:36 config
-rw-r--r-- 1 wwwrun www  3691 Apr 26 05:00 console.php
drwxr-xr-x 1 wwwrun www   312 Apr 26 05:04 core
-rw-r--r-- 1 wwwrun www  5919 Apr 26 05:00 cron.php
drwxrwx--- 1 wwwrun www   138 Apr 26 11:35 data
-rw-r--r-- 1 wwwrun www 32727 Apr 26 05:00 db_structure.xml
-rw-r--r-- 1 wwwrun www   179 Apr 26 05:00 index.html
-rw-r--r-- 1 wwwrun www  2026 Apr 26 05:00 index.php
drwxr-xr-x 1 wwwrun www    58 Apr 26 05:00 l10n
drwxr-xr-x 1 wwwrun www    78 Apr 26 05:00 lib
-rwxr-xr-x 1 wwwrun www   283 Apr 26 05:00 occ
drwxr-xr-x 1 wwwrun www    70 Apr 26 05:00 ocs
drwxr-xr-x 1 wwwrun www    42 Apr 26 05:00 ocs-provider
-rw-r--r-- 1 wwwrun www  2969 Apr 26 05:00 public.php
-rw-r--r-- 1 wwwrun www  4599 Apr 26 05:00 remote.php
drwxr-xr-x 1 wwwrun www    60 Apr 26 05:00 resources
-rw-r--r-- 1 wwwrun www    26 Apr 26 05:00 robots.txt
drwxr-xr-x 1 wwwrun www   288 Apr 26 05:00 settings
-rw-r--r-- 1 wwwrun www  1819 Apr 26 05:00 status.php
drwxr-xr-x 1 wwwrun www    26 Apr 26 11:33 themes
drwxr-xr-x 1 wwwrun www   330 Apr 26 11:35 updater
-rw-r--r-- 1 wwwrun www   232 Apr 26 05:03 version.php
```

**Comment by LukasReschke** [comment]
@VicDeo Why is `__apps` not deleted in @PVince81's case as it is for us? 😕

**Comment by PVince81** [comment]
https://s3.owncloud.com/owncloud/index.php/s/FPFgQ2nf0bbgMIy

**Comment by PVince81** [comment]
@LukasReschke it's still stuck on "Updating core", maybe it hasn't updated the apps yet.

Note that the update is hanging on this screen:
![updater-confusion](https://cloud.githubusercontent.com/assets/277525/14814119/1dec99fa-0ba5-11e6-8d05-bfcb41448d71.png)

and CPU is stuck at 100%, maybe an infinite loop.

**Comment by PVince81** [comment]
Forgot to mention the permissions: I only did `chmod g+w owncloudtest` on the main folder, not on all subfolders. Does it matter ?

**Comment by LukasReschke** [comment]
It's not related to the repair step itself but more to the fact that in your case somehow `__apps` is still there. I'd propose:

9.0.2:
- Exclude __apps (https://github.com/owncloud/core/pull/24273)
- Store __apps in data folder in new updater code (https://github.com/owncloud/updater/issues/332) 

9.1.0:
- Move cache from integrity check to file

**Comment by PVince81** [comment]
Can we move "store __apps in data folder" to 9.0.3 ? Running out of time and there are other updater issues that need adressing

**Comment by LukasReschke** [comment]
> Can we move "store __apps in data folder" to 9.0.3 ? Running out of time and there are other updater issues that need adressing

Fair enough. But we should do this within the 9.0.x cycle :)

**Comment by PVince81** [comment]
@LukasReschke understood, I'll move the ticket to 9.0.3 then.

**Comment by PVince81** [comment]
My exact steps now, just in case:

1. Run these
```
/srv/www/htdocs # rm -Rf owncloudtest/
/srv/www/htdocs # cp -R ~vincent/temp/owncloud-9.0.0 owncloudtest
/srv/www/htdocs # chown -R wwwrun:www owncloudtest
/srv/www/htdocs # cd owncloudtest
/srv/www/htdocs/owncloudtest # mkdir -p data; chown -R wwwrun:www config data; chgrp www apps; chmod g+w apps config data
```
1. Run setup in web UI with DB "owncloudtest"
1. Go to "Updater" section in admin page
1. Switch dropdown to "daily"
1. Reload page
1. Click "Open updater"
1. Click "Start"
1. Wait

Additionally, I redid the update with the php5-pcntl module enabled to avoid the warnings, but the same symptoms appears. So the absence of this module isn't related to my issue.

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/issues/24292
