### ISSUE TITLE
Update 9.1.0 to 9.1.1RC1 fails

### ISSUE THREAD

**Issue by PVince81** [owncloud/updater#371]
I wanted to enable updated for 9.1.1RC1 in the update server but when I did I met this issue (reproduced at least twice):

1. Setup v9.1.0
1. Update URL to match local update server
1. Switch to beta channel
1. Update to v9.1.1RC1

```
[info] Execution of upgrade:detect command started
[info] ownCloud 9.1.0.15 found
[info] Execution of upgrade:detect command stopped. Exit code is 0
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0
[info] Execution of upgrade:checkpoint command started
[info] Execution of upgrade:checkpoint command stopped. Exit code is 0
[info] Execution of upgrade:detect command started
[info] ownCloud 9.1.0.15 found
[info] Execution of upgrade:detect command stopped. Exit code is 0
[info] Execution of upgrade:disableNotShippedApps command started
[info] Execution of upgrade:disableNotShippedApps command stopped. Exit code is 0
[info] Execution of upgrade:executeCoreUpgradeScripts command started
[debug] Replacing 3rdparty
[debug] Replacing config
[debug] Replacing core
[debug] Replacing l10n
[debug] Replacing lib
[debug] Replacing ocs
[debug] Replacing ocs-provider
[debug] Replacing resources
[debug] Replacing settings
[debug] Replacing .htaccess
[debug] Replacing .mailmap
[debug] Replacing .tag
[debug] Replacing .user.ini
[debug] Replacing AUTHORS
[debug] Replacing console.php
[debug] Replacing COPYING-AGPL
[debug] Replacing cron.php
[debug] Replacing db_structure.xml
[debug] Replacing index.html
[debug] Replacing index.php
[debug] Replacing indie.json
[debug] Replacing occ
[debug] Replacing public.php
[debug] Replacing remote.php
[debug] Replacing robots.txt
[debug] Replacing status.php
[debug] Replacing version.php
[error] 

                                                                                                                                         
  [GuzzleHttp\Exception\ServerException]                                                                                                 
  Server error response [url] http://localhost/owncloudtest/index.php/occ/upgrade [status code] 503 [reason phrase] Service Unavailable  
                                                                                                                                         


Exception trace:
 () at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
 GuzzleHttp\Exception\RequestException::create() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php:33
 GuzzleHttp\Subscriber\HttpError->onComplete() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/Event/Emitter.php:109
 GuzzleHttp\Event\Emitter->emit() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:91
 GuzzleHttp\RequestFsm->__invoke() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:132
 GuzzleHttp\RequestFsm->GuzzleHttp\{closure}() at /srv/www/htdocs/owncloudtest/updater/vendor/react/promise/src/FulfilledPromise.php:25
 React\Promise\FulfilledPromise->then() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55
 GuzzleHttp\Ring\Future\CompletedFutureValue->then() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php:43
 GuzzleHttp\Message\FutureResponse::proxy() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:135
 GuzzleHttp\RequestFsm->__invoke() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Client->send() at /srv/www/htdocs/owncloudtest/updater/src/Utils/OccRunner.php:103
 Owncloud\Updater\Utils\OccRunner->runAsRequest() at /srv/www/htdocs/owncloudtest/updater/src/Utils/OccRunner.php:70
 Owncloud\Updater\Utils\OccRunner->run() at /srv/www/htdocs/owncloudtest/updater/src/Command/ExecuteCoreUpgradeScriptsCommand.php:118
 Owncloud\Updater\Command\ExecuteCoreUpgradeScriptsCommand->execute() at /srv/www/htdocs/owncloudtest/updater/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /srv/www/htdocs/owncloudtest/updater/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at /srv/www/htdocs/owncloudtest/updater/src/Console/Application.php:197
 Owncloud\Updater\Console\Application->doRunCommand() at /srv/www/htdocs/owncloudtest/updater/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /srv/www/htdocs/owncloudtest/updater/src/Console/Application.php:174
 Owncloud\Updater\Console\Application->doRun() at /srv/www/htdocs/owncloudtest/updater/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /srv/www/htdocs/owncloudtest/updater/src/Controller/IndexController.php:150
 Owncloud\Updater\Controller\IndexController->ajaxAction() at /srv/www/htdocs/owncloudtest/updater/src/Controller/IndexController.php:88
 Owncloud\Updater\Controller\IndexController->dispatch() at /srv/www/htdocs/owncloudtest/updater/index.php:29


upgrade:executeCoreUpgradeScripts
```

For some reason "occ" from the owncloud server responds 503.

@VicDeo please investigate

**Comment by PVince81** [comment]
@VicDeo any update ?

**Comment by VicDeo** [comment]
@PVince81 owncloud.log is also needed here.
for me it is: 
```
{"reqId":"MviqEjr7gR8xa7jLDcZe","remoteAddr":"::1","app":"index","message":"
Exception: {
"Exception":"OC\NeedsUpdateException",
"Message":"",
"Code":0,
"Trace":"
#0 /9.1.0/lib/private/legacy/app.php(119): OC_App::loadApp('dav')
#1 /9.1.0/lib/private/legacy/util.php(135): OC_App::loadApps(Array)
#2 /9.1.0/lib/base.php(890): OC_Util::setupFS()
#3 /9.1.0/index.php(39): OC::handleRequest()
#4{main}
",
"File":"/9.1.0/lib/private/legacy/app.php","Line":147}",
"level":3,
"time":"2016-09-06T19:27:06+00:00",
"method":"POST",
"url":"/9.1.0/index.php/occ/upgrade",
"user":"--"
}
```
