### ISSUE TITLE
9.1.5 to 10.0.(0|1) - Internal server error

### ISSUE THREAD

**Issue by VicDeo** [owncloud/updater#424]
```
{"reqId":"wHMFEp3yZfM0nfP8JNcv","level":3,"time":"2017-05-19T12:56:07+00:00","remoteAddr":"127.0.0.1","user":"--","app":"index","method":"POST","url":"\/10rc3\/index.php\/occ\/upgrade","message":"Exception: {\"Exception\":\"Doctrine\DBAL\Exception\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM "oc_accounts" WHERE "lower_user_id" = :dcValue1':\
\
SQLSTATE[HY000]: General error: 1 no such table: oc_accounts\",\"Code\":0,\"Trace\":\"#0 10rc3/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 10rc3/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(804): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM "...')
#2 10rc3/lib/private/DB/Connection.php(168): Doctrine\DBAL\Connection->prepare('SELECT * FROM "...')
#3 10rc3/lib/public/AppFramework/Db/Mapper.php(235): OC\DB\Connection->prepare('SELECT * FROM "...', NULL, NULL)
#4 10rc3/lib/public/AppFramework/Db/Mapper.php(285): OCP\AppFramework\Db\Mapper->execute('SELECT * FROM `...', Array, NULL, NULL)
#5 10rc3/lib/public/AppFramework/Db/Mapper.php(379): OCP\AppFramework\Db\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)
#6 10rc3/lib/private/User/AccountMapper.php(124): OCP\AppFramework\Db\Mapper->findEntity('SELECT * FROM `...', Array)
#7 10rc3/lib/private/User/Manager.php(155): OC\User\AccountMapper->getByUid(NULL)
#8 10rc3/lib/private/Group/Manager.php(472): OC\User\Manager->get(NULL)
#9 10rc3/lib/private/legacy/user.php(326): OC\Group\Manager->inGroup(NULL, 'admin')
#10 10rc3/lib/private/AppFramework/DependencyInjection/DIContainer.php(450): OC_User::isAdminUser(NULL)
#11 10rc3/lib/private/AppFramework/DependencyInjection/DIContainer.php(354): OC\AppFramework\DependencyInjection\DIContainer->isAdminUser()
#12 10rc3/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\AppFramework\DependencyInjection\DIContainer->OC\AppFramework\DependencyInjection\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#13 10rc3/lib/private/AppFramework/DependencyInjection/DIContainer.php(389): Pimple\Container->offsetGet('SecurityMiddlew...')
#14 10rc3/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\AppFramework\DependencyInjection\DIContainer->OC\AppFramework\DependencyInjection\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#15 10rc3/lib/private/AppFramework/DependencyInjection/DIContainer.php(334): Pimple\Container->offsetGet('MiddlewareDispa...')
#16 10rc3/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\AppFramework\DependencyInjection\DIContainer->OC\AppFramework\DependencyInjection\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#17 10rc3/lib/
private/AppFramework/App.php(90): Pimple\Container->offsetGet('Dispatcher')
#18 10rc3/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('OC\\Core\\Control...', 'execute', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#19 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#20 10rc3/lib/private/Route/Router.php(299): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#21 10rc3/lib/base.php(922): OC\Route\Router->match('/occ/upgrade')
#22 10rc3/index.php(49): OC::handleRequest()
#23 {main}\",\"File\":\"10rc3/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php\",\"Line\":58}"}
```

**Comment by VicDeo** [comment]
Fixed with https://github.com/owncloud/core/issues/27965
