### ISSUE TITLE
[QA] update from 10.13.4 fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/updater#743]
Seen with owncloud core 10.13.4 and updater-1.1.1-rc.1 (and bundled updater-1.1.0, thus not a regression!)

* manually replace /var/www/owncloud/updater with the unpacked contents of updater-1.1.1-rc.1
* trigger cron.
* a notification appears, that 10.14.0 is available.
* in the admin web ui click: run updater
* an error message appears:
```
Server error: `POST https://oc10134-up20240620r-v111rc1-date.jw-qa.owncloud.works/index.php/occ/config:list` resulted in a `500 Internal Server Error` response: <!DOCTYPE html> <html class="ng-csp" data-placeholder-focus="false" lang="en" > <head data-requesttoken=""> <meta cha (truncated...) 
```

Server log has
```
{"reqId":"ZnQxIIwKbjiAmxxLTcgJ6AAAAAA","level":3,"time":"2024-06-20T13:39:44+00:00","remoteAddr":"23.88.45.83","user":"--","app":"index","method":"POST","url":"\/index.php\/occ\/config:list","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'Symfony\\\\Component\\\\Serializer\\\\Normalizer\\\\ObjectNormalizer' not found\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DataExporter\\\\Serializer->__construct()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(73): ReflectionClass->newInstanceArgs()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(89): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(109): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(63): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(89): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(109): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(63): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(89): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(109): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(79): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query()\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Console\\\/Application.php(171): OC\\\\ServerContainer->query()\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Console\\\/Application.php(112): OC\\\\Console\\\\Application->loadCommandsFromInfoXml()\\n#13 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/OccController.php(107): OC\\\\Console\\\\Application->loadCommands()\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OC\\\\Core\\\\Controller\\\\OccController->execute()\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/kernel.php(913): OC\\\\Route\\\\Router->match()\\n#20 \\\/var\\\/www\\\/owncloud\\\/index.php(32): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps-external\\\/data_exporter\\\/lib\\\/Serializer.php\",\"Line\":39}"}
{"reqId":"QjrESysgplQbLvy8YXHH","level":1,"time":"2024-06-20T13:40:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"--","url":"--","message":"Invalidating tokens older than 2024-06-20T13:20:01+00:00"}

```

**Comment by DeepDiver1975** [comment]
> \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/data_exporter\\\/lib\\\/Serializer.php

looks like an issue with the data_exporter ....

**Comment by jnweiger** [comment]
Ah, I failed to mention that I have data_exporter installed and enabled in that system. Sorry.

**Comment by iasdeoupxe** [comment]
https://doc.owncloud.com/server/10.15/admin_manual/maintenance/upgrading/manual_upgrade.html#review-third-party-apps
